//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public int Id { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nick { get; set; }
        public string Mail { get; set; }
        public string Usługa { get; set; }
        public Nullable<System.DateTime> DataZakupu { get; set; }
        public Nullable<System.DateTime> DataZakonczenieUsługi { get; set; }
        public Nullable<int> IloscAbonamentowRocznych { get; set; }
        public string SkadPozyskany { get; set; }
        public string Ulica { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string TelefonKomorkowy { get; set; }
        public string TelefonStacjonarny { get; set; }
        public string StronaWWW { get; set; }
        public string NazwaFirmy { get; set; }
        public string Uwagi { get; set; }
        public string Inne { get; set; }
        public Nullable<bool> Friend { get; set; }
    }
}
